---
- name: Update web servers
  hosts: web
  become: yes

  tasks:
  - name: Ensure git is installed
    yum:
      name: git
      state: installed

  - name: Ensure myntra is started
    git:
      repo: https://github.com/ravi2krishna/ecomm.git
      dest: /var/www/html/

...
